import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import * as React from 'react';
import { NavLink, Outlet, useLocation } from 'react-router-dom';
import { LayoutDashboard, Compass, BookmarkCheck, Briefcase, FileText, Video, Bot, Settings, ChevronLeft, ChevronRight, Menu, Bell, Search, CheckCircle2, Radio, } from 'lucide-react';
import { cn } from '../lib/cn';
import { Badge } from '../components/ui/badge';
import { Modal } from '../components/ui/modal';
import { Drawer } from '../components/ui/drawer';
import { Input } from '../components/ui/input';
import { useHealthQuery } from '../hooks/use-health';
const navItems = [
    { label: 'Dashboard', path: '/', icon: LayoutDashboard },
    { label: 'Discover Jobs', path: '/discover', icon: Compass },
    { label: 'Saved Jobs', path: '/saved-jobs', icon: BookmarkCheck },
    { label: 'Applications', path: '/applications', icon: Briefcase },
    { label: 'Resumes', path: '/resumes', icon: FileText },
    { label: 'Interviews', path: '/interviews', icon: Video },
    { label: 'Agent Activity', path: '/agent-activity', icon: Bot },
    { label: 'Settings', path: '/settings', icon: Settings },
];
export function AppLayout() {
    const [isSidebarCollapsed, setIsSidebarCollapsed] = React.useState(false);
    const [isMobileOpen, setIsMobileOpen] = React.useState(false);
    const [isSearchOpen, setIsSearchOpen] = React.useState(false);
    const [isNotificationsOpen, setIsNotificationsOpen] = React.useState(false);
    const [searchQuery, setSearchQuery] = React.useState('');
    const location = useLocation();
    const { data: healthData, isError: isHealthError } = useHealthQuery();
    const currentNav = navItems.find((item) => item.path === location.pathname ||
        (item.path !== '/' && location.pathname.startsWith(item.path)));
    return (_jsxs("div", { className: "flex h-screen w-full overflow-hidden bg-slate-950 text-slate-100", children: [_jsxs("aside", { className: cn('hidden md:flex flex-col border-r border-slate-800/80 bg-slate-900/90 transition-all duration-300 relative z-20', isSidebarCollapsed ? 'w-16' : 'w-64'), children: [_jsxs("div", { className: "flex h-16 items-center justify-between px-4 border-b border-slate-800/80", children: [_jsxs("div", { className: "flex items-center gap-3 overflow-hidden", children: [_jsx("div", { className: "flex h-9 w-9 items-center justify-center rounded-xl bg-gradient-to-br from-indigo-500 to-indigo-700 text-white font-bold shadow-md shadow-indigo-600/30 flex-shrink-0", children: "SK" }), !isSidebarCollapsed ? (_jsxs("div", { className: "flex flex-col truncate", children: [_jsx("span", { className: "text-sm font-bold tracking-tight text-white", children: "SK JobPilot" }), _jsx("span", { className: "text-[10px] font-semibold tracking-wider text-indigo-400 uppercase", children: "AI Copilot" })] })) : null] }), _jsx("button", { onClick: () => setIsSidebarCollapsed((prev) => !prev), className: "hidden md:flex h-7 w-7 items-center justify-center rounded-lg border border-slate-800 bg-slate-900 text-slate-400 hover:bg-slate-800 hover:text-white transition-colors", title: isSidebarCollapsed ? 'Expand Sidebar' : 'Collapse Sidebar', children: isSidebarCollapsed ? (_jsx(ChevronRight, { className: "h-4 w-4" })) : (_jsx(ChevronLeft, { className: "h-4 w-4" })) })] }), _jsx("nav", { className: "flex-1 space-y-1 p-3 overflow-y-auto", children: navItems.map((item) => {
                            const Icon = item.icon;
                            return (_jsxs(NavLink, { to: item.path, className: ({ isActive }) => cn('flex items-center gap-3 rounded-lg px-3 py-2.5 text-xs font-semibold transition-all group', isActive
                                    ? 'bg-indigo-600/15 text-indigo-400 border border-indigo-500/30 shadow-sm'
                                    : 'text-slate-400 hover:bg-slate-800/60 hover:text-slate-100'), title: isSidebarCollapsed ? item.label : undefined, children: [_jsx(Icon, { className: "h-4 w-4 flex-shrink-0" }), !isSidebarCollapsed ? _jsx("span", { children: item.label }) : null] }, item.path));
                        }) }), _jsx("div", { className: "p-3 border-t border-slate-800/80 bg-slate-950/40", children: !isSidebarCollapsed ? (_jsxs("div", { className: "rounded-lg border border-slate-800 p-2.5 bg-slate-900/60 flex items-center justify-between", children: [_jsxs("div", { className: "flex items-center gap-2", children: [_jsx(Radio, { className: cn('h-3.5 w-3.5 animate-pulse', !isHealthError ? 'text-emerald-400' : 'text-rose-400') }), _jsxs("div", { className: "flex flex-col", children: [_jsx("span", { className: "text-[10px] uppercase font-bold text-slate-400", children: "Backend API" }), _jsx("span", { className: "text-xs font-medium text-slate-200", children: !isHealthError && healthData ? 'Connected' : 'Offline / Mock' })] })] }), _jsx(Badge, { variant: !isHealthError ? 'success' : 'danger', children: !isHealthError ? 'v1.0' : 'OFF' })] })) : (_jsx("div", { className: "flex justify-center", title: "API Status", children: _jsx(Radio, { className: cn('h-4 w-4 animate-pulse', !isHealthError ? 'text-emerald-400' : 'text-rose-400') }) })) })] }), _jsx(Drawer, { isOpen: isMobileOpen, onClose: () => setIsMobileOpen(false), side: "left", title: "SK JobPilot Menu", children: _jsx("nav", { className: "space-y-1.5 pt-2", children: navItems.map((item) => {
                        const Icon = item.icon;
                        return (_jsxs(NavLink, { to: item.path, onClick: () => setIsMobileOpen(false), className: ({ isActive }) => cn('flex items-center gap-3 rounded-lg px-3 py-3 text-sm font-semibold transition-all', isActive
                                ? 'bg-indigo-600/20 text-indigo-400 border border-indigo-500/30'
                                : 'text-slate-300 hover:bg-slate-800'), children: [_jsx(Icon, { className: "h-5 w-5" }), _jsx("span", { children: item.label })] }, item.path));
                    }) }) }), _jsxs("div", { className: "flex flex-1 flex-col overflow-hidden", children: [_jsxs("header", { className: "flex h-16 items-center justify-between border-b border-slate-800/80 bg-slate-900/60 px-4 md:px-6 backdrop-blur-md z-10", children: [_jsxs("div", { className: "flex items-center gap-3", children: [_jsx("button", { onClick: () => setIsMobileOpen(true), className: "md:hidden rounded-lg p-2 text-slate-400 hover:bg-slate-800 hover:text-white", children: _jsx(Menu, { className: "h-5 w-5" }) }), _jsxs("div", { className: "flex items-center gap-2", children: [_jsx("h2", { className: "text-base font-bold text-slate-100", children: currentNav?.label || 'SK JobPilot' }), _jsx(Badge, { variant: "warning", className: "hidden sm:inline-flex bg-amber-500/10 text-amber-400 border-amber-500/20 text-[10px] uppercase font-bold tracking-wider", children: "DEV SAMPLE DATA" })] })] }), _jsxs("div", { className: "flex items-center gap-3", children: [_jsxs("button", { onClick: () => setIsSearchOpen(true), className: "flex items-center gap-2 rounded-lg border border-slate-800 bg-slate-950/80 px-3 py-1.5 text-xs text-slate-400 hover:border-slate-700 hover:text-slate-200 transition-all", children: [_jsx(Search, { className: "h-3.5 w-3.5" }), _jsx("span", { className: "hidden sm:inline", children: "Search jobs, skills..." }), _jsx("kbd", { className: "hidden sm:inline-block rounded border border-slate-800 bg-slate-900 px-1.5 text-[10px] text-slate-400", children: "\u2318K" })] }), _jsxs("button", { onClick: () => setIsNotificationsOpen(true), className: "relative rounded-lg border border-slate-800 bg-slate-900/80 p-2 text-slate-400 hover:border-slate-700 hover:text-white transition-colors", children: [_jsx(Bell, { className: "h-4 w-4" }), _jsx("span", { className: "absolute top-1 right-1 h-2 w-2 rounded-full bg-indigo-500 ring-2 ring-slate-950" })] })] })] }), _jsx("main", { className: "flex-1 overflow-y-auto p-4 md:p-6 lg:p-8 bg-slate-950", children: _jsx(Outlet, {}) })] }), _jsx(Modal, { isOpen: isSearchOpen, onClose: () => setIsSearchOpen(false), title: "Global Search", maxWidth: "lg", children: _jsxs("div", { className: "space-y-4", children: [_jsx(Input, { placeholder: "Type a title, skill, or company...", leftIcon: _jsx(Search, { className: "h-4 w-4" }), value: searchQuery, onChange: (e) => setSearchQuery(e.target.value), autoFocus: true }), _jsxs("div", { className: "rounded-lg border border-slate-800 bg-slate-950 p-4 text-center", children: [_jsx("p", { className: "text-xs text-slate-400", children: searchQuery
                                        ? `Showing preview matches for "${searchQuery}"`
                                        : 'Enter keywords to search across jobs and applications.' }), _jsxs("div", { className: "mt-3 flex justify-center gap-2", children: [_jsx(Badge, { variant: "outline", children: "React" }), _jsx(Badge, { variant: "outline", children: "Node.js" }), _jsx(Badge, { variant: "outline", children: "TypeScript" })] })] })] }) }), _jsx(Drawer, { isOpen: isNotificationsOpen, onClose: () => setIsNotificationsOpen(false), side: "right", title: "Notifications", children: _jsxs("div", { className: "space-y-3 pt-2", children: [_jsxs("div", { className: "rounded-lg border border-slate-800 bg-slate-950/80 p-3", children: [_jsxs("div", { className: "flex items-center gap-2 text-indigo-400 text-xs font-semibold mb-1", children: [_jsx(Bot, { className: "h-4 w-4" }), " Discovery Agent"] }), _jsx("p", { className: "text-xs text-slate-300", children: "5 new High-Match Senior TypeScript jobs discovered." }), _jsx("span", { className: "text-[10px] text-slate-400 mt-2 block", children: "10 minutes ago" })] }), _jsxs("div", { className: "rounded-lg border border-slate-800 bg-slate-950/80 p-3", children: [_jsxs("div", { className: "flex items-center gap-2 text-emerald-400 text-xs font-semibold mb-1", children: [_jsx(CheckCircle2, { className: "h-4 w-4" }), " Tailor Agent"] }), _jsx("p", { className: "text-xs text-slate-300", children: "Resume tailored for \"Lead AI Architect\" at TechCorp." }), _jsx("span", { className: "text-[10px] text-slate-400 mt-2 block", children: "1 hour ago" })] })] }) })] }));
}
//# sourceMappingURL=app-layout.js.map